milestone-5 event-handlers
sz16900/calculator-react pull request #7
Opened 2020-08-11 14:59 UTC by sz16900

- add click handler events to the app, button and button panel
- final touch-ups
- final wiring
- catch division by zero error

2020-08-11 19:45 UTC, Forison requested changes
## Status:: Changes required❌.
# 🙋‍♂️ Seth
#### You have done a great job on this one, your project meets most the technical requirements, but there are a few functional issues we have to address to make the application user friendly and output correct info to the user🙍‍♂️.
* [x] I am unable to perform decimal computation ie ```0.4 + 0.4  ```
* [x] The styling should enable the user to see all the inputted value even the exceed the length of the display screen. 
Check the image below👇
![overflow](https://user-images.githubusercontent.com/29695661/89940831-2487da00-dbe8-11ea-93b3-1a4b6a338898.png)
Make the digit break or shrink size when the length increases.
* [x] Use Object destructuring to efficiently obtain your data instead of  ```const copyObject = this.state; ```
 in your App.js
* [x] Let use ES6 syntax to avoid having to bind methods we create 
```this.handleClick = this.handleClick.bind(this); ```
We can define ```handleClick = () => { }``` this way to avoid binding.

**[OPTIONAL REQUIREMENT ]**

* [ ] It will more user friendly to have the current operation selected appear somewhere on the screen so the user can see what is happening.

### That is it kindly make these changes and submit a re-review👨‍🔧.

#### Happy coding👨‍💻

Addo Forison

2020-08-12 12:28 UTC, suretrust requested changes
Hi @sz16900, 👋 

### Great job implementing some of the suggested changes! 🙌 Please see my comments. 👇 

- [ ]  I am still unable to perform decimal computation ie `0.4` + `0.4`. `0.anything` is not even pressing.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-12 12:28 UTC, suretrust commented on src/components/App.js
> +    this.setState(calcResult);
You can use React's `prevState` for this. You could read more about it [here](https://stackoverflow.com/questions/54807454/what-is-prevstate-in-reactjs). This is completely optional, just pointing it out for future reference.

```suggestion
    this.setState(prevState => ({
        calculate(prevState, buttonName)
    }))
}));
```

2020-08-13 10:39 UTC, shshamim63 approved these changes
## :100: Approved
___
Hi @sz16900 :wave: ,
Congratulation, you have successfully resolve the bug, now it is working properly. Nothing is blocking me from approving this project. Great job :clap: . You can go ahead and merge it.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-08-13 12:35 UTC, merged